@url = http://localhost:3001/api
@json = Content-Type: application/json

###list all the users 
GET {{url}}/findUsers

### regiseter
POST {{url}}/register
{{json}}

{
    "username":"user3",
    "password":"123456"
}

### login
POST {{url}}/login
{{json}}

{
    "username":"usr3",
    "password":"123456"
}

### personal info
GET {{url}}/userinfo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODZlZmQ0MjgwMGE0NDA2MDU5NWIyMCIsImlhdCI6MTYwMjY3OTk4OH0.DOEBLdS35FXoTMoCK0qAKd9eWMRLOikg6QU_5zLLr2Y